### ISSUE TITLE
Immutable return

### ISSUE THREAD

**Issue by barak007** [75lb/array-back#3]
Hello, 
I just stumble upon this library and I'm not sure if it matters but in the case that you pass and array to this method you get the same array back (not as a clone). 
In all other cases it creates a new array. Maybe consider to slice a new array from the input that will make this function immutable. 
Maybe it should be a parameter to not break existing code.

**Comment by 75lb** [comment]
Yes, it returns the same array back. This is by design because the input array could be a 1gb array of database records - cloning this would be slow and expensive and not something the library should do by default.. 

There's no need to pass an option to the library to trigger a clone, just clone the array yourself..

**Comment by barak007** [comment]
Maybe I'm just poking here but the same argument is valid for set and array like object.

**Comment by 75lb** [comment]
it's not.. neither a `Set` or an "arraylike" (an object literal with a `length` property) is an `Array`.. the library guarantees an array back, so in those two cases needs to create one..
